---
name: Build / Push ECR / Deploy - dev

permissions:
  id-token: write
  contents: read

on:
  push:
    branches:
      - main
    paths:
      - ''
      - '!.github/workflows/'
      - '.github/workflows/ecr.yml'
      - '.github/workflows/default.yml'

jobs:

  build:
    uses: ./.github/workflows/ecr.yml
    with:
      runs-on: ubuntu-latest
      aws-region: ${{ vars.AWS_REGION }}
      role-to-assume: ${{ vars.AWS_IAM_ROLE_ARN }}
      ecr-repo-name: ${{ vars.ECR_REPO_NAME }}
      default-tag: ${{ vars.DEFAULT_TAG }}
      image-tag: ${{ github.sha }}
      image-param: ${{ vars.BOT_WEBHOOK_IMAGE_PARAM_DEV }}

  deploy:
    name:
    runs-on: ubuntu-latest
    needs: [ build ]
    steps:

      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Deploy Infra
        uses: ./.github/actions/repo-dispatch
        with:
          aws-region: ${{ vars.AWS_REGION }}
          role-to-assume: ${{ vars.AWS_IAM_ROLE_ARN }}
          token-param: ${{ vars.INFRA_TOKEN_PARAM }}
          repository: ${{ vars.INFRA_GITHUB_REPO }}
          event-type: dev
