---
name: Build and push to ECR

permissions:
  id-token: write
  contents: read

on:
  release:
    types: [ published ]
    paths:
      - ''
      - '!.github/workflows/'
      - '.github/workflows/ecr.yml'
      - '.github/workflows/release.yml'

jobs:

  build_and_push:
    uses: ./.github/workflows/ecr.yml
    with:
      runs-on: ubuntu-latest
      aws-region: ${{ vars.AWS_REGION }}
      role-to-assume: ${{ vars.IAM_ROLE_ARN }}
      ecr-repo-name: ${{ vars.ECR_REPO_NAME }}
      image-tag: ${{ github.ref_name }}
