---
name: Build / Push ECR / Deploy - live

permissions:
  id-token: write
  contents: read

on:
  release:
    types: [ published ]
    paths:
      - ''
      - '!.github/workflows/'
      - '.github/workflows/ecr.yml'
      - '.github/workflows/release.yml'

jobs:

  build:
    uses: ./.github/workflows/ecr.yml
    with:
      runs-on: ubuntu-latest
      aws-region: ${{ vars.AWS_REGION }}
      role-to-assume: ${{ vars.AWS_IAM_ROLE_ARN }}
      ecr-repo-name: ${{ vars.ECR_REPO_NAME }}
      image-tag: ${{ github.ref_name }}
      image-param: ${{ vars.BOT_WEBHOOK_IMAGE_PARAM_LIVE }}
