---
name: Build / Push ECR / Deploy - live

permissions:
  id-token: write
  contents: read

on:
  release:
    types: [ published ]

jobs:

  build:
    uses: ./.github/workflows/ecr.yml
    with:
      runs-on: ubuntu-latest
      aws-region: ${{ vars.AWS_REGION }}
      role-to-assume: ${{ vars.AWS_IAM_ROLE_ARN }}
      ecr-repo-name: ${{ vars.ECR_REPO_NAME }}
      image-tag: ${{ github.ref_name }}
      image-param: ${{ vars.BOT_WEBHOOK_IMAGE_PARAM_LIVE }}

  deploy:
    runs-on: ubuntu-latest
    environment: live
    needs: [ build ]
    steps:

      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Trigger Infra Deploy
        uses: ./.github/actions/repo-dispatch
        with:
          aws-region: ${{ vars.AWS_REGION }}
          role-to-assume: ${{ vars.AWS_IAM_ROLE_ARN }}
          token-param: ${{ vars.INFRA_TOKEN_PARAM }}
          repository: ${{ vars.INFRA_GITHUB_REPO }}
          event-type: live
